Lab-2
Alerrom/web-programming-5-sem pull request #2
Opened 2022-09-26 09:18 UTC by Alerrom

Результат работы в рамках 2 лабораторной работы

2022-09-26 11:39 UTC, BakasaRus requested changes
1. Не хватает `line-height`
2.

2022-09-26 11:39 UTC, BakasaRus commented on css/text.css
> +* {
`*` не рекомендуется использовать в качестве селектора, лучше поменять

2022-09-26 11:39 UTC, BakasaRus commented on css/text.css
> +    font-family: 'Times New Roman', Times, serif;
Шрифт тянуть с Google Fonts, можно не Times New Roman

2022-09-26 11:39 UTC, BakasaRus commented on css/text.css
> +    font-size: 20px;
Какие единицы ещё используются для задания размера и что лучше использовать для размера шрифта?

2022-09-26 11:39 UTC, BakasaRus commented on css/ascii_logo.css
> +    font-family:monospace;
Что за `monospace`?

2022-09-26 11:39 UTC, BakasaRus commented on css/text.css
> +    font-weight: 200;
Чтобы это работало, нужен шрифт с соответствующей поддержкой

2022-09-26 17:04 UTC, Alerrom commented on css/ascii_logo.css
> +    font-family:monospace;
Это моноширный шрифт, т.е. все знаки в нем имеют одну ширину.
Конкретно данная штука, как я понял, вытаскивает в общем виде какой-то моноширный шрифт. Можно указать какое-то конкретное семейство

2022-09-26 17:24 UTC, Alerrom commented on css/text.css
> +    font-size: 20px;
px - это один пиксель. Как я понял, другие ЕИ все равно будут переводиться в px. Если размер получился дробным в px, то он округлиться.
Есть всякие mm, cm, pt, pc. Но так как они конвертируются в пиксели, то проще задавать сразу в пикселях.
Есть em - штука, которая позволяет задавать относительные размеры шрифта. Так, например, можно во вложенных тегах постепенно увеличить/уменьшить размер текста. 1em - текущий размер шрифта, который считается в зависимости от формата отрисовки шрифта.
Можно указывать % от размера родительского класса.
Есть еще штуки по типу rem (задаёт размер относительно размера шрифта элемента) и vw/vh (1% ширины/высоты окна). Это хорошо подойдет для случаем, когда пользователь захочет масштабировать экран.
Поэтому мне кажется, что лучше для шрифта использовать пиксели, % и всякие rem/vh/vw. Первым мы будем строго задавать размеры для десктопной версии, а другими шаманить, чтобы результат корректно отображался на других устройствах.

2022-10-09 20:57 UTC, BakasaRus approved these changes

2022-10-10 13:03 UTC, merged