Lab 3
Alerrom/web-programming-5-sem pull request #3
Opened 2022-10-27 14:43 UTC by Alerrom

Добавил таблицу (grid и table), настроил float, position и @media screen

2022-10-31 12:09 UTC, BakasaRus requested changes
1. Галерею с книжками лучше переделать на flexbox
2. Вспомни про `fr`
3. Табличку лучше переделать на grid-систему
4. Почитай про различные способы вёрстки (кроме гридов и флексов)
5. В идеале меню на маленьких экранах должно быть колоночным
6. Почитай про [viewport](https://developer.mozilla.org/ru/docs/Glossary/Viewport)

2022-11-06 15:39 UTC, Alerrom commented
fr - это единица измерения (по типу px, %): fractional unit или дробная единица. Глобально (как я понял) она автоматически рассчитывает ширину элемента относительно ширины экрана. Это позволяет не хардкодить формулы. Причем можно использовать и дробные значения (0.5fr, 3.1fr), если потребуется сохранить пропорцию между элементами

2022-11-06 15:44 UTC, Alerrom commented
Из старых типов верстки вспомнил про фреймы. Это когда мы несколько экранов прокрутки отображаем на одном экране
Про табличную вроде тоже не говорил. Здесь мы размещаем по ячейкам контент так, как нам удобно. Но вроде логично, что таблицы изначально создавались для табличных данных, а не для размещения контента
Гибкая/адаптивная вертка - про нее как раз рассказывал (с использованием grid, F и Z, 12-столбчатая)

2022-11-07 11:06 UTC, BakasaRus approved these changes

2022-11-11 11:43 UTC, merged