Lab 4
Alerrom/web-programming-5-sem pull request #4
Opened 2022-11-14 22:07 UTC by Alerrom

2022-11-14 22:11 UTC, Alerrom commented
На маленьких экранах меню теперь сворачивается
При загрузке страницы в подвале указано время загрузки
Анимация подсветки элементов меню реализована через CSS

2022-11-21 12:29 UTC, BakasaRus requested changes
Не хватает подсветки текущего пункта меню именно через JS

2022-11-21 12:29 UTC, BakasaRus commented on javascript/config.js
> +    event => handleLocationChange(document.location.href, '#1CC5FA', '#000000'));
![говно-переделывай](https://user-images.githubusercontent.com/21131366/201672285-1d6870e6-b031-4e8d-b11d-810484a7a9c7.gif)

2022-11-21 12:29 UTC, BakasaRus commented on javascript/menuNavigation.js
> +        header.className += " responsive";
Вот тут лучше через `classList`

2022-12-12 11:37 UTC, BakasaRus approved these changes

2022-12-18 14:35 UTC, merged